export default [
  {
    title: 'nav.Wallet_Generator',
    titleMobi: 'nav.Wallet_Generator___mobi',
    description: 'nav.Wallet_Generator_',
    path: '/wallet/generator',
    icon: ['fas', 'wallet'],
    class: 'btn btn-pink',
    textClass: 'text-pink-200',
  },
  {
    title: 'nav.Wallet_Validator',
    titleMobi: 'nav.Wallet_Validator___mobi',
    description: 'nav.Wallet_Validator_',
    path: '/wallet/validator',
    icon: ['fas', 'spell-check'],
    class: 'btn btn-gray',
    textClass: 'text-gray-200',
  },
  {
    title: 'nav.Wallet_Public_Key',
    titleMobi: 'nav.Wallet_Public_Key___mobi',
    description: 'nav.Wallet_Public_Key_',
    path: '/wallet/public-key',
    icon: ['fas', 'key'],
    class: 'btn',
    textClass: 'text-indigo-200',
  },
  {
    title: 'nav.Wallet_Private_Key',
    titleMobi: 'nav.Wallet_Private_Key___mobi',
    description: 'nav.Wallet_Private_Key_',
    path: '/wallet/private-key',
    icon: ['fas', 'fingerprint'],
    class: 'btn',
    textClass: 'text-indigo-200',
  },
  {
    title: 'nav.Wallet_Bind',
    titleMobi: 'nav.Wallet_Bind___mobi',
    description: 'nav.Wallet_Bind_',
    path: '/wallet/bind',
    icon: ['fas', 'link'],
    class: 'btn btn-pink',
    textClass: 'text-pink-200',
  },
  // {
  //   title: 'nav.Avatar',
  //   description: 'nav.Avatar_',
  //   path: 'avatar',
  //   icon: ['far', 'smile-wink']
  // },
]
