name: Build & Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  auto-deploy:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 14 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup node env
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install
        run: yarn

      - name: Build (voken1000g.github.io/toolkit)
        run: yarn build-repo

      - name: Deploy (voken1000g.github.io/toolkit)
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          commit-message: "@${{ github.sha }}"
          branch: gh-pages
          folder: dist

      - name: Clear
        run: rm -rf ./dist

      - name: Build (toolkit.voken.io)
        run: yarn build

      - name: CNAME (toolkit.voken.io)
        run: echo "toolkit.voken.io" > ./dist/CNAME

      - name: Deploy (toolkit.voken.io)
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository-name: voken1000g/toolkit.voken.io
          commit-message: "${{ github.repository }}@${{ github.sha }}"
          branch: main
          folder: dist

      - name: CNAME (get.voken.io)
        run: echo "get.voken.io" > ./dist/CNAME

      - name: Deploy (get.voken.io)
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository-name: voken1000g/get.voken.io
          commit-message: "${{ github.repository }}@${{ github.sha }}"
          branch: get
          folder: dist
