name: Build & Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  auto-deploy:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 14 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup node env
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install
        run: yarn

      # voken1000g.github.io/early-bird
      - name: Write repo.js
        run: echo export default \'early-bird\' > repo.js

      - name: Build (voken1000g.github.io/early-bird)
        run: yarn build-repo-early-bird

      - name: Deploy (voken1000g.github.io/early-bird)
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository-name: voken1000g/early-bird
          commit-message: "${{ github.repository }}@${{ github.sha }}"
          branch: repo-early-bird
          folder: dist

      # Clear /dist
      - name: Clear
        run: rm -rf ./dist

      # Clear repo.js
      - name: Clear
        run: rm repo.js

      # toolkit.voken.io
      - name: Build (toolkit.voken.io)
        run: yarn build

      - name: CNAME (toolkit.voken.io)
        run: echo "toolkit.voken.io" > ./dist/CNAME

      - name: Deploy (toolkit.voken.io)
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository-name: voken1000g/toolkit.voken.io
          commit-message: "${{ github.repository }}@${{ github.sha }}"
          branch: main
          folder: dist

      # Remove repo.js
      - name: Remove repo.js
        run: rm repo.js

      # migrate.voken.io
      - name: CNAME (migrate.voken.io)
        run: echo "migrate.voken.io" > ./dist/CNAME

      - name: Deploy (migrate.voken.io)
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository-name: voken1000g/migrate.voken.io
          commit-message: "${{ github.repository }}@${{ github.sha }}"
          branch: migrate
          folder: dist

      # early-bird.voken.io
      - name: CNAME (early-bird.voken.io)
        run: echo "get.voken.io" > ./dist/CNAME

      - name: Deploy (early-bird.voken.io)
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository-name: voken1000g/early-bird.voken.io
          commit-message: "${{ github.repository }}@${{ github.sha }}"
          branch: early-bird
          folder: dist

      # get.voken.io
      - name: CNAME (get.voken.io)
        run: echo "get.voken.io" > ./dist/CNAME

      - name: Deploy (get.voken.io)
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository-name: voken1000g/get.voken.io
          commit-message: "${{ github.repository }}@${{ github.sha }}"
          branch: get
          folder: dist

      # voken1000g.github.io/toolkit
      - name: Clear
        run: rm -rf ./dist

      - name: Write repo.js
        run: echo export default \'toolkit\' > repo.js

      - name: Build (voken1000g.github.io/toolkit)
        run: yarn build-repo

      - name: Deploy (voken1000g.github.io/toolkit)
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          commit-message: "@${{ github.sha }}"
          branch: gh-pages
          folder: dist
